stages:
  - build
  - test

variables:
  GIT_STRATEGY: fetch
  GIT_CLEAN_FLAGS: "-xdfq --exclude=dist --exclude=node_modules"

build:
  stage: build
  tags:
    - dsa
    - DIND
  image: node:20
  script:
    - npm ci
    - npm run build

test:
  stage: test
  tags:
    - dsa
    - DIND
  image: node:20
  script:
    - npm ci
    - npm run build:lib
    - npm run build
    - npx playwright install-deps
    - npx playwright install
    - npm run lint
    - npm run test:lib
    - npx kill-port 4200
    - nohup npm run start & sleep 30
    - npm run test:ci
    - npm run test:ci:percy
    - npx kill-port 4200
