stages:
  - build
  - test

variables:
  GIT_STRATEGY: fetch
  GIT_CLEAN_FLAGS: "-xdfq --exclude=dist --exclude=node_modules"

build:
  stage: build
  tags:
    - dsa
    - DIND
  image: node:20
  script:
    - npm ci
    - npm run build

test:
  stage: test
  tags:
    - dsa
    - DIND
  image: node:20
  script:
    - npm ci
    - npm run lint
    - npx puppeteer browsers install chrome
    - npm run test:ci
    - npx playwright install chromium --with-deps
    - nohup npm run start &
    - sleep 28 && npm run test:lib
    - npm run test:ci:percy
    - npx kill-port 4200
