stages:
  - build
  - test

variables:
  GIT_STRATEGY: fetch
  GIT_CLEAN_FLAGS: "-xdfq --exclude=dist --exclude=node_modules"

build:
  stage: build
  tags:
    - dsa
    - DIND
  image: node:20
  script:
    - npm ci
    - npm run build

test:
  stage: test
  tags:
    - dsa
    - DIND
  image: node:20
  script:
    - npm run lint
    - npm run test
