language:
  node_js
  - 9
cache:
  directories:
    - node_modules
install:
  - npm install
before_script:
  - npm install -g @angular/cli codecov
script:
  - npm run lint
  - npm run build
  - npm run test
after_success:
  - codecov
