/**
 * @license
 * (c) 2016 Infor. All rights reserved. www.infor.com
 *
 * NOTICE
 *
 * THIS SOFTWARE IS THE PROPERTY OF AND CONTAINS
 * CONFIDENTIAL INFORMATION OF INFOR AND/OR ITS AFFILIATES
 * OR SUBSIDIARIES AND SHALL NOT BE DISCLOSED WITHOUT PRIOR
 * WRITTEN PERMISSION. LICENSED CUSTOMERS MAY COPY AND
 * ADAPT THIS SOFTWARE FOR THEIR OWN USE IN ACCORDANCE WITH
 * THE TERMS OF THEIR SOFTWARE LICENSE AGREEMENT.
 * ALL OTHER RIGHTS RESERVED.
 *
 * (c) COPYRIGHT 2016 INFOR.  ALL RIGHTS RESERVED.
 * THE WORD AND DESIGN MARKS SET FORTH HEREIN ARE
 * TRADEMARKS AND/OR REGISTERED TRADEMARKS OF INFOR
 * AND/OR ITS AFFILIATES AND SUBSIDIARIES. ALL RIGHTS
 * RESERVED.  ALL OTHER TRADEMARKS LISTED HEREIN ARE
 * THE PROPERTY OF THEIR RESPECTIVE OWNERS.
 */

/// <reference path="./src/soho/soho.d.ts" />

declare var System: any;

/**
 * @module
 * @description
 * Entry point for all public APIs of the common package.
 */
export * from './src/soho';
