export * from './soho-icon.component';
export * from './soho-icons.component';
export * from './soho-icons-empty.component';
export * from './soho-icons-extended.component';
export * from './soho-icons-uplift.component';
export * from './soho-icons-empty-uplift.component';
export * from './soho-icons-new.component';
export * from './soho-icons-empty-new.component';
export * from './soho-icon.module';
